language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-restify-live' ]; then cd .. && eval "mv $currentfolder generator-restify-live" && cd generator-restify-live; fi

